/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

 /*
  * Author : Rohit Pawar
  * Assignment 2 : Implementation of RPC Principle
  * Client Program request server to execute some task 
  *
 */
#include "RPC.h"


void
interface_1(char *host)
{
	CLIENT *clnt;
	my_string  *result_1;
	char *pwd_command_to_retrieve_path_1_arg;
	my_integer_one_dimensional_array  *result_2;
	my_integer_one_dimensional_array  sort_1_arg;
	my_string  *result_3;
	my_string  echo_client_1_arg;
	my_string  *result_4;
	my_string  check_file_exist_1_arg;
	my_integer_two_dimensional_array  *result_5;
	matrix_multiplication_input  matrixmultiplication_1_arg;

#ifndef	DEBUG
	//UDP transport service is used 
	clnt = clnt_create (host, Interface, Interface_Version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	int choice;
	char str[100];
	int i,j;

	do
	{
		//Menu 
		printf ("\n 1. Return Current Directory Path \n 2. Sort Array  \n 3. Echo Client \n 4. Check if File Exist \n 5. Matrix Multiplication \n 6. Exit \n Enter your choice:");
		scanf("%d",&choice);
		
		switch (choice)
		{
			case 1:
				//request to get current working directory path
				result_1 = pwd_command_to_retrieve_path_1((void*)&pwd_command_to_retrieve_path_1_arg, clnt);
				if (result_1 == (my_string *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else
				{
					printf("\n Current Working Directory at Server:%s \n",result_1->data);
				}
				break;
				
			case 2:
				//sort given input array
				printf("\n Enter Array Size:");
				scanf("%d",&sort_1_arg.size);
				for (i=0;i<sort_1_arg.size;i++)
				{
					printf("\n Enter number %d:",i+1);
					scanf("%d",&sort_1_arg.data[i]);
				}
				result_2 = sort_1(&sort_1_arg, clnt);
				if (result_2 == (my_integer_one_dimensional_array *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else
				{
					printf("\n Sorted List \n");
					for(i=0;i<result_2->size;i++)
					{
						printf(" %d\t",result_2->data[i]);
					}
				}
				break;
				
			case 3:
				// echo client
				printf("\n Enter String:");
				scanf(" %[^\t\n]s",str);
				echo_client_1_arg.data = str;

				result_3 = echo_client_1(&echo_client_1_arg, clnt);
				if (result_3 == (my_string *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else
				{
					printf("\n Echo:%s \n",result_3->data);
				}
				break;
				
			case 4:
				//Request to check specified file is present or not
				printf("\n Enter File Name:");
				scanf("%s",str);
				check_file_exist_1_arg.data = str;

				result_4 = check_file_exist_1(&check_file_exist_1_arg, clnt);
				if (result_4 == (my_string *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else
				{
					printf("\n %s:%s \n",str,result_4->data);
				}
				break;
				
			case 5:
				// Matrix Multiplication
				//Matrix 1 Input Range
				printf(" Enter number of rows for matrix1:");
				scanf("%d",&matrixmultiplication_1_arg.matrix1.row);
				
				printf(" Enter number of columns for matrix1:");
				scanf("%d",&matrixmultiplication_1_arg.matrix1.column);
				
				//Matrix 2 Input Range
				printf(" Enter number of rows for matrix2:");
				scanf("%d",&matrixmultiplication_1_arg.matrix2.row);
				
				printf(" Enter number of columns for matrix2:");
				scanf("%d",&matrixmultiplication_1_arg.matrix2.column);
				
				//Necessary condition to carry out matrix multiplication
				if (matrixmultiplication_1_arg.matrix1.column != matrixmultiplication_1_arg.matrix2.row) 
				{
					printf("\n Matrix1 columns %d did not match matrix2 rows %d \n", matrixmultiplication_1_arg.matrix1.column , matrixmultiplication_1_arg.matrix2.row);
					break;
				}
				
				//Matrix 1 Input
				int matrix1_size = matrixmultiplication_1_arg.matrix1.row*matrixmultiplication_1_arg.matrix1.column;
				printf(" Enter %d numbers for matrix1\n",matrix1_size);
				for(i=0;i<matrix1_size;i++)
				{
					scanf("%d",&matrixmultiplication_1_arg.matrix1.data[i]);
				}
				
				//Matrix 2 Input
				int matrix2_size = matrixmultiplication_1_arg.matrix2.row*matrixmultiplication_1_arg.matrix2.column;
				printf(" Enter %d numbers for matrix2\n",matrix2_size);
				for(i=0;i<matrix2_size;i++)
				{
					scanf("%d",&matrixmultiplication_1_arg.matrix2.data[i]);
				}
			
				//request for matrix multiplication
				result_5 = matrixmultiplication_1(&matrixmultiplication_1_arg, clnt);
				if (result_5 == (my_integer_two_dimensional_array *) NULL) {
					clnt_perror (clnt, "call failed");
				}
				else
				{
					printf ("\n Result Matrix\n");
					for(i=0;i<result_5->row;i++)
					{
						for(j=0;j<result_5->column;j++)
						{
							printf(" %d\t",result_5->data[i*result_5->column+j]);	
						}
						printf("\n");
					}
				}
				break;
			case 6:
				//Terminate client
				printf("\n Exit");
				break;
			default: printf("\n Wrong choice \n");
		}
	}while(choice!=6);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	interface_1 (host);
exit (0);
}
