/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_string (XDR *xdrs, my_string *objp)
{
	register int32_t *buf;

	 if (!xdr_str_t (xdrs, &objp->data))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_integer_one_dimensional_array (XDR *xdrs, my_integer_one_dimensional_array *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->data, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->size);
			{
				register int *genp;

				for (i = 0, genp = objp->data;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->size))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->data, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->size = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->data;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_integer_two_dimensional_array (XDR *xdrs, my_integer_two_dimensional_array *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (2 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->row))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->column))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->data, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->row);
			IXDR_PUT_LONG(buf, objp->column);
			{
				register int *genp;

				for (i = 0, genp = objp->data;
					i < 100; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (2 +  100 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->row))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->column))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->data, 100,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->row = IXDR_GET_LONG(buf);
			objp->column = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->data;
					i < 100; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->row))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->column))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->data, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_matrix_multiplication_input (XDR *xdrs, matrix_multiplication_input *objp)
{
	register int32_t *buf;

	 if (!xdr_my_integer_two_dimensional_array (xdrs, &objp->matrix1))
		 return FALSE;
	 if (!xdr_my_integer_two_dimensional_array (xdrs, &objp->matrix2))
		 return FALSE;
	return TRUE;
}
